highlighter: rouge
linenos: true
highlight:
  linenos: true
highlight_options:
  linenos: true

markdown: kramdown

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-octicons
  - jekyll-seo-tag

webmaster_verifications:
  google: pwPztJ8mLIFCyqUhQTXZ8OoeaVx9CL3mXqQkVWlQsgY
