highlighter: rouge
linenos: true
highlight:
  linenos: true
highlight_options:
  linenos: true

markdown: kramdown
kramdown:
  input: GFM
  extensions:
    - autolink

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-octicons
  - jekyll-seo-tag
  - jekyll-gist

webmaster_verifications:
  google: pwPztJ8mLIFCyqUhQTXZ8OoeaVx9CL3mXqQkVWlQsgY
